### PR TITLE
fixing pin# mistake in code comments

### PR DESCRIPTION
**Pull request by mechatroniks-git**

### CODE REVIEW

**Review by darraghbr — CHANGES_REQUESTED** [review]
I believe you have PB0 and PB1 the wrong way around from one another. 

image

image

**Comment by mechatroniks-git** [comment]
That is the V0.3 PCB, which the firmware hasn't been committed yet (still working on it). This comment update was for the v0.2 firmware
image

**Comment by darraghbr** [comment]
Right ok, that may cause some confusion, is the intention to have this commit labelled under the 0.2 release?

**Comment by mechatroniks-git** [comment]
Yes, I think I need to make sure 0.2 is perfect before I can start committing 0.3

**Review by mmroden — APPROVED** [review]
good for 0.2, comments will change for 0.3 etc

**Review by darraghbr — APPROVED** [review]

**Pull request merged**
