### PR TITLE
V0.3 firmware

### PR DESCRIPTION
**Pull request by mechatroniks-git**

### CODE REVIEW

**Comment by darraghbr** [comment]
Is the plan to merge this first, create a 0.3 release then merge the 0.4?

**Comment by mechatroniks-git** [comment]
> Is the plan to merge this first, create a 0.3 release then merge the 0.4?

That or we move the firmware repo per #19

**Review by darraghbr — CHANGES_REQUESTED** [review]
Just need to change the README to remove the reference to the ArduinoConfig.PNG and then tag this as the release for 0.3. Might need to get @capsulecorplab to resolve some of the conflicts.

**Review by darraghbr — APPROVED** [review]

**Comment by capsulecorplab** [comment]
Yeah, I would probably do a rebase off main, resolve conflicts during the rebase, then force-push changes

**Comment by capsulecorplab** [comment]
@mechatroniks-git is https://github.com/tetrabiodistributed/PAPRA-PCB/blob/e4e49f00775b911907105ec34b31b21c4d7eb426/README.md the most up-to-date chip list?

**Comment by capsulecorplab** [comment]
Pushed a new branch at https://github.com/tetrabiodistributed/PAPRA-PCB/tree/v0.3-firmware-resolve-conflicts. If it looks good, I can update this PR to match that

**Comment by darraghbr** [comment]
> 
> 
> Pushed a new branch at https://github.com/tetrabiodistributed/PAPRA-PCB/tree/v0.3-firmware-resolve-conflicts. If it looks good, I can update this PR to match that

Only difference I can see is in the README 

<html><body>


Model number | Confirmed | Notes
-- | -- | --
ATtiny204SSN_, | Yes | See note below


</body>
</html>

Should be 

<html><body>


Model number | Confirmed | Notes
-- | -- | --
ATtiny204SSN_, | Yes | Support SerialEvent must be 'no'


</body>
</html>

**Comment by capsulecorplab** [comment]
@darraghbr note updated https://github.com/tetrabiodistributed/PAPRA-PCB/commit/32544dded7d0e149c6ad50cba3776a66479493bc

**Comment by darraghbr** [comment]
> 
> 
> @darraghbr note updated [32544dd](https://github.com/tetrabiodistributed/PAPRA-PCB/commit/32544dded7d0e149c6ad50cba3776a66479493bc)

LGTM

**Comment by capsulecorplab** [comment]
PR updated. You may merge when ready...

**Comment by darraghbr** [comment]
mergewhenready

**Pull request merged**
