### PR TITLE
Adding in drawings for the PCBA

### PR DESCRIPTION
**Pull request by darraghbr**
Addresses #15 and #17

### CODE REVIEW

**Review by mechatroniks-git — COMMENTED** [review]
Showing "Empty file"

**Comment by darraghbr** [comment]
> 
> 
> Showing "Empty file"

I don't know why it's doing this, if you hit the 3 dots to the right of the file and hit view file it will show you.

**Comment by mechatroniks-git** [comment]
But the 2 pdf files in 527563b are good, so not sure why they are showing empty here.

**Comment by darraghbr** [comment]
Not sure, if you are happy with it merge it and we'll see if it breaks anything?

**Pull request merged**
